apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-slow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-slow
  template:
    metadata:
      labels:
        app: fastapi-slow
    spec:
      containers:
        - name: app
          image: afoley587/coding-challenges/fastapi-otel
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4318"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://jaeger:4318/v1/traces"
            - name: OTEL_SERVICE_NAME
              value: "fastapi-demo-bottlenecks"
          args:
            - python
            - slow.py

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-slow
spec:
  selector:
    app: fastapi-slow
  ports:
    - port: 8000
      targetPort: 8000
